#!/usr/bin/env python3
"""
Генератор hosts файла для разблокировки AI сервисов
Резолвит домены через Cloudflare DNS и создаёт hosts файл

Использование:
  python generate-hosts.py                    # Вывод в консоль
  python generate-hosts.py -o hosts.txt       # Сохранить в файл
  python generate-hosts.py --apply            # Применить к системе (требует sudo)
"""

import argparse
import socket
import sys
from pathlib import Path

# Домены AI сервисов для разблокировки
AI_DOMAINS = [
    # OpenAI
    "chatgpt.com",
    "chat.openai.com",
    "openai.com",
    "api.openai.com",

    # Google Gemini
    "gemini.google.com",
    "aistudio.google.com",
    "generativelanguage.googleapis.com",
    "ai.google.dev",

    # Google Antigravity
    "antigravity.google",

    # Claude
    "claude.ai",
    "anthropic.com",
    "api.anthropic.com",

    # Grok
    "grok.x.ai",
    "x.ai",

    # Perplexity
    "perplexity.ai",
    "api.perplexity.ai",

    # Mistral
    "mistral.ai",
    "chat.mistral.ai",
]


def resolve_domain(domain: str) -> str | None:
    """Резолвит домен в IP через системный DNS"""
    try:
        ip = socket.gethostbyname(domain)
        return ip
    except socket.gaierror:
        return None


def generate_hosts_content() -> str:
    """Генерирует содержимое hosts файла"""
    lines = [
        "# AI Services - Generated by generate-hosts.py",
        "# Добавить в конец файла:",
        "#   Windows: C:\\Windows\\System32\\drivers\\etc\\hosts",
        "#   Linux/Mac: /etc/hosts",
        "",
    ]

    resolved = 0
    failed = []

    for domain in AI_DOMAINS:
        ip = resolve_domain(domain)
        if ip:
            lines.append(f"{ip}\t{domain}")
            resolved += 1
        else:
            failed.append(domain)
            lines.append(f"# FAILED: {domain}")

    lines.append("")
    lines.append(f"# Resolved: {resolved}/{len(AI_DOMAINS)} domains")
    if failed:
        lines.append(f"# Failed: {', '.join(failed)}")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Генератор hosts для AI сервисов")
    parser.add_argument("-o", "--output", help="Файл для сохранения")
    parser.add_argument("--apply", action="store_true", help="Применить к системе (sudo)")
    args = parser.parse_args()

    content = generate_hosts_content()

    if args.output:
        Path(args.output).write_text(content, encoding="utf-8")
        print(f"[OK] Сохранено в {args.output}")
    elif args.apply:
        # Определяем путь hosts
        if sys.platform == "win32":
            hosts_path = Path("C:/Windows/System32/drivers/etc/hosts")
        else:
            hosts_path = Path("/etc/hosts")

        print(f"[!] Для применения выполните:")
        print(f"    sudo bash -c 'cat >> {hosts_path} << EOF")
        print(content)
        print("EOF'")
    else:
        print(content)


if __name__ == "__main__":
    main()
